FROM debian:latest
MAINTAINER steven velozo

RUN echo "...installing debian dependencies..."
RUN apt update
RUN apt install vim curl tmux -y

RUN echo "Building service image..."

RUN echo "...configuring mariadb (mysql) server...."
RUN apt install default-mysql-server default-mysql-client -y
RUN sed -i "s|bind-address|#bind-address|g" /etc/mysql/mariadb.conf.d/50-server.cnf
ADD ./source/model/mysql_create/MySQL-Configure-Security.sql /home/coder/MySQL-Configure-Security.sql
ADD ./docker_scripts/MySQL-Laden-Entry.sh /usr/bin/MySQL-Laden-Entry.sh
RUN ( mysqld_safe --skip-grant-tables --skip-networking & ) && sleep 5 && mysql -u root < /home/coder/MySQL-Configure-Security.sql

# Import the initial database
COPY ./source/model/mysql_create/MeadowModel-CreateMySQLDatabase.mysql.sql /home/coder/MeadowModel-CreateMySQLDatabase.mysql.sql
COPY ./source/model/mysql_create/MeadowModel-PopulateDatabase.sql /home/coder/MeadowModel-PopulateDatabase.sql

RUN service mariadb restart && sleep 5 && mysql -u root -p"123456789" -e "CREATE DATABASE bookstore;"
RUN service mariadb restart && sleep 5 && mysql -u root -p"123456789" bookstore < /home/coder/MeadowModel-CreateMySQLDatabase.mysql.sql
RUN service mariadb restart && sleep 5 && mysql -u root -p"123456789" bookstore < /home/coder/MeadowModel-PopulateDatabase.sql

RUN echo "...mapping library specific volumes..."

VOLUME /retold-harness

SHELL ["/bin/bash", "-c"]

RUN echo "...installing node version manager..."

# Because there is a .bashrc chicken/egg problem, we will create one here to simulate logging in.  This is not great.
RUN touch /root/.bashrc && chmod +x /root/.bashrc
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

ENV NODE_VERSION=20
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN . /root/.nvm/nvm.sh && source /root/.bashrc && node --version
RUN . /root/.nvm/nvm.sh && npm --version

WORKDIR /retold-harness

RUN echo "...configuring entrypoint..."

COPY ./docker_scripts/MySQL-Laden-Entry-ServicesOnly.sh /root/MySQL-Laden-Entry-ServicesOnly.sh
ENTRYPOINT ["/root/MySQL-Laden-Entry-ServicesOnly.sh"]
