# Use the codercom/code-server image for the VS Code browser IDE
FROM codercom/code-server:latest
LABEL maintainer="steven velozo <steven@velozo.com>"

VOLUME /home/coder/.config
VOLUME /home/coder/.vscode

RUN echo "...installing debian dependencies..."
RUN sudo apt update
RUN sudo apt install vim curl tmux -y

RUN echo "Building development image..."

# Volume mapping for code
VOLUME /home/coder/retold-harness

SHELL ["/bin/bash", "-c"]
USER coder

RUN echo "...installing node version manager..."
RUN touch ~/.bashrc && chmod +x ~/.bashrc
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN chmod +x ~/.nvm/nvm.sh

RUN echo "...installing node version 20 as the default..."
RUN . ~/.nvm/nvm.sh && source ~/.bashrc && nvm install 20
RUN . ~/.nvm/nvm.sh && source ~/.bashrc && nvm alias default 20

WORKDIR /home/coder/retold-harness

COPY --chmod=755 ./docker_scripts/Entry.sh /usr/bin/Entry.sh
ENTRYPOINT ["/usr/bin/Entry.sh"]
