graph TD
	A[Retold-Harness.js] --> B[Schema Provider]
	A --> C[Provider Configurator]
	B --> D[Bookstore Schema]
	B --> E[US Federal Data Schema]
	B --> F[Entertainment Schema]
	C --> G[SQLite Provider]
	C --> H[MySQL Provider]
	C --> I[MSSQL Provider]
	C --> J[PostgreSQL Provider]
	C --> K[MongoDB Provider]
	C --> L[DGraph Provider]
	C --> M[Solr Provider]
	C --> N[Retold Data Service]
	N --> O[Orator HTTP Server]
	N --> P[Meadow DAL]
	N --> Q[Meadow Endpoints]
	Q --> R[Behavior Injection]
