-- US Federal Data - SQLite Table Definitions
-- 10 tables: User, DataSource, CensusRegion, CensusDivision, State, County,
--            City, ZIPCode, CongressionalDistrict, CountySubdivision

CREATE TABLE IF NOT EXISTS User
(
	IDUser INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDUser INTEGER DEFAULT 0,
	LoginID TEXT DEFAULT '',
	Password TEXT DEFAULT '',
	NameFirst TEXT DEFAULT '',
	NameLast TEXT DEFAULT '',
	FullName TEXT DEFAULT '',
	Config TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS DataSource
(
	IDDataSource INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDDataSource TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	URL TEXT DEFAULT '',
	Description TEXT DEFAULT '',
	FileFormat TEXT DEFAULT '',
	Vintage TEXT DEFAULT '',
	LastRetrieved TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS CensusRegion
(
	IDCensusRegion INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCensusRegion TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	RegionCode INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CensusDivision
(
	IDCensusDivision INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCensusDivision TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	DivisionCode INTEGER DEFAULT 0,
	IDCensusRegion INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS State
(
	IDState INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDState TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	Abbreviation TEXT DEFAULT '',
	StateFIPS INTEGER DEFAULT 0,
	ANSI INTEGER DEFAULT 0,
	IDCensusRegion INTEGER DEFAULT 0,
	IDCensusDivision INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS County
(
	IDCounty INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCounty TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	StateFIPS INTEGER DEFAULT 0,
	CountyFIPS INTEGER DEFAULT 0,
	ClassFP TEXT DEFAULT '',
	IDState INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS City
(
	IDCity INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCity TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	USPS TEXT DEFAULT '',
	GEOID INTEGER DEFAULT 0,
	ANSICODE INTEGER DEFAULT 0,
	LSAD TEXT DEFAULT '',
	FunctionalStatus TEXT DEFAULT '',
	LandArea INTEGER DEFAULT 0,
	WaterArea INTEGER DEFAULT 0,
	LandAreaSqMi REAL DEFAULT 0,
	WaterAreaSqMi REAL DEFAULT 0,
	Latitude REAL DEFAULT 0,
	Longitude REAL DEFAULT 0,
	IDState INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ZIPCode
(
	IDZIPCode INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDZIPCode TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	ZIPCode TEXT DEFAULT '',
	GEOID INTEGER DEFAULT 0,
	LandArea INTEGER DEFAULT 0,
	WaterArea INTEGER DEFAULT 0,
	LandAreaSqMi REAL DEFAULT 0,
	WaterAreaSqMi REAL DEFAULT 0,
	Latitude REAL DEFAULT 0,
	Longitude REAL DEFAULT 0,
	IDState INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CongressionalDistrict
(
	IDCongressionalDistrict INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCongressionalDistrict TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	USPS TEXT DEFAULT '',
	GEOID INTEGER DEFAULT 0,
	LSAD TEXT DEFAULT '',
	Congress TEXT DEFAULT '',
	FunctionalStatus TEXT DEFAULT '',
	LandArea INTEGER DEFAULT 0,
	WaterArea INTEGER DEFAULT 0,
	LandAreaSqMi REAL DEFAULT 0,
	WaterAreaSqMi REAL DEFAULT 0,
	Latitude REAL DEFAULT 0,
	Longitude REAL DEFAULT 0,
	IDState INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CountySubdivision
(
	IDCountySubdivision INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDCountySubdivision TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	USPS TEXT DEFAULT '',
	GEOID INTEGER DEFAULT 0,
	ANSICODE INTEGER DEFAULT 0,
	LSAD TEXT DEFAULT '',
	FunctionalStatus TEXT DEFAULT '',
	LandArea INTEGER DEFAULT 0,
	WaterArea INTEGER DEFAULT 0,
	LandAreaSqMi REAL DEFAULT 0,
	WaterAreaSqMi REAL DEFAULT 0,
	Latitude REAL DEFAULT 0,
	Longitude REAL DEFAULT 0,
	IDState INTEGER DEFAULT 0,
	IDCounty INTEGER DEFAULT 0
);
