-- Entertainment Schema - SQLite Table Definitions
-- 16 tables: User, DataSource, Genre, Person, Movie, MovieGenre, MovieCredit,
--            MovieRating, Artist, Album, Song, AlbumTrack, Soundtrack,
--            Venue, Concert, SetlistEntry

CREATE TABLE IF NOT EXISTS User
(
	IDUser INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDUser INTEGER DEFAULT 0,
	LoginID TEXT DEFAULT '',
	Password TEXT DEFAULT '',
	NameFirst TEXT DEFAULT '',
	NameLast TEXT DEFAULT '',
	FullName TEXT DEFAULT '',
	Config TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS DataSource
(
	IDDataSource INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDDataSource TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	URL TEXT DEFAULT '',
	Description TEXT DEFAULT '',
	FileFormat TEXT DEFAULT '',
	Vintage TEXT DEFAULT '',
	LastRetrieved TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Genre
(
	IDGenre INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDGenre TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	Category TEXT DEFAULT '',
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Person
(
	IDPerson INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDPerson TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	ExternalID TEXT DEFAULT '',
	BirthYear INTEGER DEFAULT 0,
	DeathYear INTEGER DEFAULT 0,
	PrimaryProfessions TEXT DEFAULT '',
	KnownForTitles TEXT DEFAULT '',
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Movie
(
	IDMovie INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDMovie TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Title TEXT DEFAULT '',
	OriginalTitle TEXT DEFAULT '',
	ExternalID TEXT DEFAULT '',
	IsAdult INTEGER DEFAULT 0,
	StartYear INTEGER DEFAULT 0,
	EndYear INTEGER DEFAULT 0,
	RuntimeMinutes INTEGER DEFAULT 0,
	GenreList TEXT DEFAULT '',
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MovieGenre
(
	IDMovieGenre INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDMovieGenre TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	IDMovie INTEGER DEFAULT 0,
	IDGenre INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MovieCredit
(
	IDMovieCredit INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDMovieCredit TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Ordering INTEGER DEFAULT 0,
	Category TEXT DEFAULT '',
	Job TEXT DEFAULT '',
	Characters TEXT DEFAULT '',
	IDMovie INTEGER DEFAULT 0,
	IDPerson INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MovieRating
(
	IDMovieRating INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDMovieRating TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	AverageRating REAL DEFAULT 0,
	NumVotes INTEGER DEFAULT 0,
	IDMovie INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Artist
(
	IDArtist INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDArtist TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	SortName TEXT DEFAULT '',
	ExternalID TEXT DEFAULT '',
	ArtistType TEXT DEFAULT '',
	BeginYear INTEGER DEFAULT 0,
	EndYear INTEGER DEFAULT 0,
	Country TEXT DEFAULT '',
	Disambiguation TEXT DEFAULT '',
	IDPerson INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Album
(
	IDAlbum INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDAlbum TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Title TEXT DEFAULT '',
	ExternalID TEXT DEFAULT '',
	AlbumType TEXT DEFAULT '',
	ReleaseYear INTEGER DEFAULT 0,
	Country TEXT DEFAULT '',
	TrackCount INTEGER DEFAULT 0,
	IDArtist INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Song
(
	IDSong INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDSong TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Title TEXT DEFAULT '',
	ExternalID TEXT DEFAULT '',
	DurationSeconds INTEGER DEFAULT 0,
	ReleaseYear INTEGER DEFAULT 0,
	IDArtist INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS AlbumTrack
(
	IDAlbumTrack INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDAlbumTrack TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	TrackNumber INTEGER DEFAULT 0,
	DiscNumber TEXT DEFAULT '',
	IDAlbum INTEGER DEFAULT 0,
	IDSong INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Soundtrack
(
	IDSoundtrack INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDSoundtrack TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Role TEXT DEFAULT '',
	Composer TEXT DEFAULT '',
	IDMovie INTEGER DEFAULT 0,
	IDSong INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Venue
(
	IDVenue INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDVenue TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	City TEXT DEFAULT '',
	State TEXT DEFAULT '',
	Country TEXT DEFAULT '',
	Latitude REAL DEFAULT 0,
	Longitude REAL DEFAULT 0,
	Capacity INTEGER DEFAULT 0,
	ExternalID TEXT DEFAULT '',
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Concert
(
	IDConcert INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDConcert TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Name TEXT DEFAULT '',
	EventDate TEXT DEFAULT '',
	TourName TEXT DEFAULT '',
	IDArtist INTEGER DEFAULT 0,
	IDVenue INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SetlistEntry
(
	IDSetlistEntry INTEGER PRIMARY KEY AUTOINCREMENT,
	GUIDSetlistEntry TEXT DEFAULT '',
	CreateDate TEXT DEFAULT '',
	CreatingIDUser INTEGER DEFAULT 0,
	UpdateDate TEXT DEFAULT '',
	UpdatingIDUser INTEGER DEFAULT 0,
	Deleted INTEGER DEFAULT 0,
	DeleteDate TEXT DEFAULT '',
	DeletingIDUser INTEGER DEFAULT 0,
	Position INTEGER DEFAULT 0,
	IsEncore INTEGER DEFAULT 0,
	Info TEXT DEFAULT '',
	IDConcert INTEGER DEFAULT 0,
	IDSong INTEGER DEFAULT 0,
	IDDataSource INTEGER DEFAULT 0
);
